### ISSUE TITLE
send message to a spawning PID may cause nil pointer dereference t:actor 

### ISSUE THREAD

**Issue by titanxxh** [asynkron/protoactor-go#198]
NewLocalPID creates a PID. If we send a message to the newly created PID between the spawn function which is executing in another goroutine, we may dereference a nil pointer of mailbox.

```
func spawn(id string, props *Props, parent *PID) (*PID, error) {
	lp := &localProcess{}
	pid, absent := ProcessRegistry.Add(lp, id) // done
	if !absent {
		return pid, ErrNameExists
	}

	cell := newLocalContext(props.actorProducer, props.getSupervisor(), props.inboundMiddleware, props.outboundMiddleware, parent)
	mb := props.produceMailbox(cell, props.getDispatcher())
	lp.mailbox = mb // not done
	var ref Process = lp
	pid.p = &ref
	cell.self = pid
	mb.Start()
	mb.PostSystemMessage(startedMessage)

	return pid, nil
}
```

**Comment by bryanpkc** [comment]
We have seen this problem before, when we called `NewLocalPID` to create a PID with a specific name and sent a message to it, before the `SpawnNamed` call with that name (on another goroutine) had finished initializing the `localProcess`. When spawning an actor without a user-specified name, it is not possible (or very hard) to construct a PID that happens to match the `localProcess` being initiailized. We decided against changing the logic in `spawn` because:

1. `NewLocalPID` is mainly used for testing. The majority of user code that uses a PID gets it through `Spawn` and `SpawnNamed`, etc., which guarantee proper initialization. We updated the godoc for `NewLocalPID` to recommend against using this function, and warn that its return value may not yet be a valid PID.

2. Let it crash: If an actor sends a message to an invalid PID obtained from `NewLocalPID`, it will panic and its supervisor can restart it, and the message can be re-tried, by which time the process will have been initialized. As stated above, this would be a rare case anyway.
