### ISSUE TITLE
An actor is running busy, and the timing tasks of other actors are not executed.

### ISSUE THREAD

**Issue by huaapp** [asynkron/protoactor-go#253]
An actor is running busy, and the timing tasks of other actors are not executed. Why? How can I locate it?
Uncertain when the mailbox is a problem, or the issue of the dispatcher

**Comment by PotterDai** [comment]
Could you post an example code about the issue? Thank you very much! = )

**Comment by devopsjedi** [comment]
Keep in mind that several actors are running within the same goroutine, so actors can effectively be blocked/delayed by other actors using too much CPU time.  I am guessing that the timing tasks are implemented as `SetReceiveTimeout` on the actor context and the action happens when the `actor.RecieveTimeout` message is received.  I had similar concerns and started using `time.AfterFunc` with closures to make sure they ran in their own goroutine and could not be delayed by other actors.
