### ISSUE TITLE
Would be great if the `RootContext` wasn't something too special, like right now. I got several places where I want either a `Context` or a `RootContext` because I want to be able to Send or Spawn.

### ISSUE THREAD

**Issue by potterdai** [asynkron/protoactor-go#274]
Would be great if the `RootContext` wasn't something too special, like right now. I got several places where I want either a `Context` or a `RootContext` because I want to be able to Send or Spawn.
I played with adding an `OuterContext` like this

```
type OuterContext interface {
	SpawnerContext
	SenderContext
}
```

which I use instead of `RootContext` and that solves most of my problems, since that allows for using either a normal Context or a RootContext, while still being able to both Spawn and Send.

_Originally posted by @emilingerslev in https://github.com/AsynkronIT/protoactor-go/pull/251_

**Comment by PotterDai** [comment]
I would also opt to tighten the root context. The root context only needs to be able to send and spawn.
Therefore it should only have the `sender` and `spawner` interface.

I would also opt for moving the message and messageHeader into a separated message interface. That would remove the ability to access a message from the root context.

It would also enable us to tighten the interfaces on some other places

_Originally posted by @Chumper in https://github.com/AsynkronIT/protoactor-go/pull/251_

**Comment by PotterDai** [comment]
Hi @emilingerslev @Chumper ,  I moved the discussion here.
The reason RootContext implements message(), messageheader(), actor() or even Parent() is because RootContext will also need to be passed into middleware, which requires SenderContext/ReceiverContext as part of its parameters.
If we slim down the RootContext, either we create a new method in middleware to accept RootContext, or we slim down SenderContext/ReceiverContext as well, both is not ideal.

@emilingerslev Just curious how did you implement the `OuterContext` ?

**Comment by emilingerslev** [comment]
I can't remember where we discussed this, but I'm pretty sure we already found a solution to this @PotterDai, right?

**Comment by rogeralsing** [comment]
In what context (pun intended) is this required?

Is it for common functions like logging or other crosscutting concerns that need to act on any layer of the infrastructure?

Any simple examples just to wrap my head around the requirements?
