### ISSUE TITLE
Bug in all-for-one stragegy

### ISSUE THREAD

**Issue by yangdiangzb** [asynkron/protoactor-go#332]
https://github.com/AsynkronIT/protoactor-go/blob/3847eb264f0a2c4a275ecdf042f8875d346f2b5e/actor/strategy_all_for_one.go#L50
		
Is there any reason that we change `message` to `child`?

**Comment by bryanpkc** [comment]
I think that is a typo. The corresponding line of code in protoactor-dotnet (https://github.com/AsynkronIT/protoactor-dotnet/blob/dev/src/Proto.Actor/Supervision.cs#L92) still says `message` instead of `child`.

**Comment by bryanpkc** [comment]
@PotterDai

**Comment by potterdai** [comment]
@yangdiangzb @bryanpkc Hey! Sorry just notice this issue!

@yangdiangzb  Thank you very much for discovering this!
This was a bug coming from Dotnet version. It has been fixed in this commit:
https://github.com/AsynkronIT/protoactor-dotnet/commit/8e5e3a14a35a900a9cbe7bf0c284b6151bcf2f22#diff-570c98f9cac58340107c8da058a103d8L156
Unfortunately Go version hasn’t been updated afterwards.

Please do go ahead and merge this!  = )

**Comment by potterdai** [comment]
@yangdiangzb Actually I’ll just merge this! Thx! = )
