### ISSUE TITLE
Logging discussion

### ISSUE THREAD

**Issue by rogeralsing** [asynkron/protoactor-go#785]
The current approach to logging in Proto.Actor comes with a lot of limitations.
If we were to improve on this, what would be the best options?
Go for a standard logging library? improve what we already have to allow new ways to subscribe to the log stream?

Going forward, OpenTelemetry is the defacto standard for observability nowadays. Otel has support for Logging, which sadly is not implemented in the Otel Go API yet.
It would be great if we in the future could point our logs to such integration and get logs and traces unified.

Suggestions here?

**Comment by Kunduin** [comment]
Until the OpenTelemetry go sdk implementation is stable, we can consider using a mature logging tool like zap. zap itself is a lightweight interface, and the underlying zapcore provides the ability to configure the encoding (e.g., BSON), add log sink (e.g., Kafka), and more. And because zap is so popular, there are many tutorials for accessing Sentry or Rollbar (it's even mentioned in the official documentation). Developers can easily adapt the log output to the apm tool they are using.

See the Configuring Zap section on zap doc at https://pkg.go.dev/go.uber.org/zap#hdr-Configuring_Zap for details.
