### ISSUE TITLE
Just curious. When is the Release 1.0?

### ISSUE THREAD

**Issue by dshyryayev** [asynkron/protoactor-go#832]
We are in process of R&D what framework or system design to choose to make our API really scalable and fault-tollerent and distributed.
There are some debates to choose AKKA or AKKA.NET or Erlang (OTP) or Elixir.
We have 4 Developers who are Golang developers, inculding myself and I am trying to figure out when protoactor-go will be finally released?

I don't think it's going to happen soon, but I am curious :)

**Comment by mkhlsvn** [comment]
👍

**Comment by stdstring** [comment]
It seems that protoactor for go is rather dead than alive.

**Comment by Tochemey** [comment]
@dshyryayev I have used Akka, Akka,NET and Erlang(OTP) in production and I can tell you they have been in existence for so long and battle tested and very good. The only downside is the licensing issue with Akka and new programming language learning curve. The Akka.Net is still free. I have played with protoactor-go for a while but never used it in a production application due to team decision not to go with it. There is more emphasis on the protoactor-net which so you may consider that as well. But as a go dev it means you need to learn C#.
I know some folks are using protoactor-go in production. You can join their slack channel and find out.
