### ISSUE TITLE
Cluster Details

### ISSUE THREAD

**Issue by mvbaffa** [asynkron/protoactor-go#86]
Hi,

Would you please give details about protoactor cluster.

- Will I be able to deploy docker containers for load balancing using the cluster ? 
- What about notifications and communications between nodes ?
- What about node down and node up notifications ?
- Will this work with a similar functionality as Akka cluster ?

Thanks

**Comment by rogeralsing** [comment]
Hi.

Cluster support works fine using Docker, it also supports a dynamic topology where nodes come an go.

Cluster notifications are sent on the EventStream, much like Akka, there are currently 5 events you can subscribe to:

### MemberJoinedEvent
Once a new node not known to the cluster, this is the event that will fire.

### MemberRejoinedEvent
Similar to the above, but is fired if a node appears with a new "Generation".
This means that the node have been killed and restarted. if this happens fast enough so that other mechanics don't have the time to react. this will ensure that the cluster sees the node as a new node.

### MemberLeftEvent
This fires when there is no trace of this node in the cluster provider anymore. 
That is, if using Consul as a cluster provider, once this node is no longer in consul, it will raise this event.

### MemberUnavailableEvent
This fires when a node is still part of the cluster, but no longer responsive.

### MemberAvailableEvent
This fires when a node that was previously unresponsive becomes responsive again.

>Will this work with a similar functionality as Akka cluster 

No, more similar to the Microsoft Orleans model.
You can however chose to use either normal Akka like actors or Orleans style Grains, or mix the two.

> What about notifications and communications between nodes ?

All nodes knows about all other nodes, and actors on different nodes can talk to eachother.
You can also use the "virtual actor" feature to have the concept of "always existing actors".
e.g. `pid := cluster.Get("MyActor","User")`
Will give you a handle to an actor named MyActor, of the type "User" (this is a named Props and not a Go or C# type name)

HTH

**Comment by rogeralsing** [comment]
One other important note is that Proto.Actor do not manage it's own cluster.
We piggyback on other cluster tools, e.g. Consul.

This means that if you are already using Consul, we are not bringing in any extra level of cluster mechanics.
All Consul tooling will work to manage your cluster.
And all of the complex mechanics of clustering is handled within Consul.

The ClusterProvider interface can be used to implement the same support over other tools, e.g. Zookeeper, ETCD and others.

**Comment by mvbaffa** [comment]
Thanks Roger,

Does the examples included in the repo have a sample of how to use the cluster?
