### ISSUE TITLE
Go 1.21 slog

### ISSUE THREAD

**Issue by rogeralsing** [asynkron/protoactor-go#936]
I would like to get rid of the old home-baked logging used in proto.actor.
Now there is proper structured logging built into go 1.21. which seems like a very good option to aim for.

It would be great if we can discuss how this transition would go, should we keep the log.go files and just replace the inner using to use slog?
How should we set up the defaults, e.g. just use slog.Default() ? or something custom?

Everyone join in and discuss

**Comment by rogeralsing** [comment]
Related: https://www.reddit.com/r/golang/comments/15ud703/how_to_use_slog_in_a_library/

**Comment by rogeralsing** [comment]
Work in progress effort:

https://github.com/asynkron/protoactor-go/pull/937

In this PR. I made it so that users can set a LoggerFactory on the actor system Config.
This allows you to tweak the logger in any way you want.
The logger instance is then stored on the actor system itself. and re-used from there for all other modules.

**Comment by nightwolfz** [comment]
This would create a convention of passing context to all actors methods in order to use the logger.
Not necessarily a bad thing....  just a heads up :)

Personally I like to keep it simple (switched custom logger to zap)

![image](https://github.com/asynkron/protoactor-go/assets/805022/df079a26-f3a4-4f20-8d5d-6a8b90600acc)
